#!/usr/bin/env bash
# Servant AI - L4 host firewall.
#
# Denies and logs all egress from the Servant container network, with one narrow
# exception for the model server. The ruleset itself is generated by app.py so it
# can be unit tested on any machine and reviewed before it is loaded.
#
#   sudo ./deploy/firewall.sh print     # show the rules, change nothing
#   sudo ./deploy/firewall.sh apply     # load the rules
#   sudo ./deploy/firewall.sh status    # rules and drop counters
#   sudo ./deploy/firewall.sh verify    # prove the model path still works
#   sudo ./deploy/firewall.sh remove    # take the rules back out
#
# Overrides: SERVANT_SUBNET, SERVANT_OLLAMA_HOST, SERVANT_OLLAMA_PORT
set -euo pipefail

ACTION="${1:-print}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP="$(dirname "$HERE")/app.py"

SUBNET="${SERVANT_SUBNET:-172.30.0.0/24}"
PORT="${SERVANT_OLLAMA_PORT:-11434}"
TABLE="servant_l4"

die() { printf 'firewall: %s\n' "$1" >&2; exit 1; }

[ -f "$APP" ] || die "cannot find app.py at $APP"
command -v python3 >/dev/null 2>&1 || die "python3 is required to generate the ruleset"

gen() {
  SUBNET="$SUBNET" PORT="$PORT" python3 - "$APP" <<'PY'
import importlib.util, os, sys
spec = importlib.util.spec_from_file_location("servant_app", sys.argv[1])
app = importlib.util.module_from_spec(spec)
try:
    spec.loader.exec_module(app)
except Exception:
    # The generator is pure string work, so a missing UI dependency must not
    # stop a sysadmin from seeing the ruleset.
    src = open(sys.argv[1], encoding="utf-8").read()
    ns = {"ipaddress": __import__("ipaddress"), "re": __import__("re")}
    start = src.index("FIREWALL_TABLE =")
    end = src.index("def chat_sections")
    exec(src[start:end], ns)
    app = type("A", (), ns)
host = os.environ.get("SERVANT_OLLAMA_HOST") or app.default_ollama_host(os.environ["SUBNET"])
sys.stdout.write(app.host_firewall_rules(os.environ["SUBNET"], host, int(os.environ["PORT"])))
PY
}

need_root() {
  [ "$(id -u)" = "0" ] || die "must run as root: sudo $0 $ACTION"
}

case "$ACTION" in
  print)
    gen
    ;;
  apply)
    need_root
    command -v nft >/dev/null 2>&1 || die "nft is not installed (apt install nftables)"
    gen > /tmp/servant-l4.nft
    # Idempotent: start from a clean copy of our own table, never flush others.
    nft delete table inet "$TABLE" 2>/dev/null || true
    nft -f /tmp/servant-l4.nft
    rm -f /tmp/servant-l4.nft
    nft list table inet "$TABLE"
    printf '\nApplied. Confirm the model still answers:\n  %s verify\n' "$0"
    ;;
  status)
    need_root
    command -v nft >/dev/null 2>&1 || die "nft is not installed"
    nft list table inet "$TABLE"
    printf '\nDrop log (journalctl):\n'
    journalctl -k -n 20 --grep "servant-l4-drop" 2>/dev/null || printf '  (no kernel log access)\n'
    ;;
  verify)
    need_root
    printf 'model reachability from the host: '
    if curl -sS -m 5 -o /dev/null "http://127.0.0.1:${PORT}/api/tags"; then
      printf 'OK\n'
    else
      printf 'FAILED - check SERVANT_OLLAMA_PORT and that Ollama is running\n'
    fi
    printf 'drop counters: '
    nft list table inet "$TABLE" 2>/dev/null | grep -c "log drop" || printf '0\n'
    printf 'run: docker compose exec servant python -c "import app; print(app.chat(\\"/\\",\\"hello\\"))"\n'
    ;;
  remove)
    need_root
    command -v nft >/dev/null 2>&1 || die "nft is not installed"
    nft delete table inet "$TABLE" 2>/dev/null && printf 'removed table %s\n' "$TABLE" \
      || printf 'table %s was not present\n' "$TABLE"
    ;;
  *)
    die "unknown action '$ACTION' (use print, apply, status, verify or remove)"
    ;;
esac
